# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!

target 'TransvectorExample' do
	pod 'Transvector', :path => '..'
end

target 'TransvectorExampleTests' do

end

target 'TransvectorExampleUITests' do

end

